"""Initial migration

Revision ID: a57e26c0e49a
Revises: 
Create Date: 2025-05-26 09:03:58.506597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a57e26c0e49a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('api_key_hash', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_users_name'), 'service_users', ['name'], unique=True)
    op.drop_index('idx_delivery_attempts_attempted_at', table_name='delivery_attempts')
    op.drop_index('idx_delivery_attempts_notification_id', table_name='delivery_attempts')
    op.drop_table('delivery_attempts')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_attempts',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('notification_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('provider_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('PENDING', 'QUEUED', 'SENDING', 'DELIVERED', 'FAILED', 'SEEN', name='notificationstatus'), autoincrement=False, nullable=False),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('attempted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('response_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], name='delivery_attempts_notification_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='delivery_attempts_pkey')
    )
    op.create_index('idx_delivery_attempts_notification_id', 'delivery_attempts', ['notification_id'], unique=False)
    op.create_index('idx_delivery_attempts_attempted_at', 'delivery_attempts', ['attempted_at'], unique=False)
    op.drop_index(op.f('ix_service_users_name'), table_name='service_users')
    op.drop_table('service_users')
    # ### end Alembic commands ###
